name = "bolt-unblocker"
account_id = "f6f64c25ba754d5b34c8bc60a98f1f06"
workers_dev = true
compatibility_date = "2025-11-10"
main = "workers-site/index.js"

[site]
bucket = "./public"
include = ["public/**/*"]
exclude = []
